### ISSUE TITLE
需要调整定时策略

### ISSUE THREAD

**Issue by if1y** [CokeMine/Auto_uclub_signin#1]
官方会在兑换时检查签到时间、言论行为。
对于签到，如果**重复出现同一个时间，会被判断为机器人，然后兑换作废，积分不退**。

建议：
**改成随机延迟执行**，不知能否实现。
我没有使用，不过看到了，顺手提个醒。

**Comment by CokeMine** [comment]
我收到消息了，不会改。因为本身这个就是写着玩的，自己也没想着要用。（

**Comment by if1y** [comment]
好的
